// v1.8 확인: 단식 주제 3 「클리어·드롭 랠리」·주제 4 「스매시 수비 → 전환」 흐름. 사용: node scripts/shot-v18.mjs
import { chromium } from "playwright-core";
import { mkdirSync } from "node:fs";
import { homedir } from "node:os";
import { join } from "node:path";
const outDir = "/tmp/v18"; mkdirSync(outDir, { recursive: true });
const browser = await chromium.launch({ executablePath: join(homedir(), ".cache/ms-playwright/chromium-1223/chrome-linux64/chrome"), headless: true, args: ["--no-sandbox"] });
const page = await browser.newPage({ viewport: { width: 390, height: 844 }, deviceScaleFactor: 2, isMobile: true, hasTouch: true });
const errors = []; page.on("pageerror", (e) => errors.push(String(e)));
let n = 0; const shot = async (name) => { n += 1; await page.screenshot({ path: join(outDir, `${String(n).padStart(2, "0")}-${name}.png`) }); };
const next = async () => { await page.getByRole("button", { name: "다음" }).click(); await page.waitForTimeout(2200); };
const pick = async (re) => { await page.getByRole("button", { name: re }).click(); await page.waitForTimeout(2300); };
const restart = async () => { await page.getByRole("button", { name: "처음", exact: true }).click(); await page.waitForTimeout(1200); };
const tab = async (re) => { await page.locator(".tab", { hasText: re }).click(); await page.waitForTimeout(2600); };
const problems = [];
const check = async (tag, expectTitle) => {
  const title = (await page.locator("#stepTitle").textContent()).trim();
  const hint = (await page.locator("#branches .est").count()) ? (await page.locator("#branches .est").textContent()).trim() : "";
  const locks = await page.locator("#branches .pct.lock").count();
  const pcts = await page.$$eval("#branches .pct", (els) => els.map((e) => e.textContent));
  const end = (await page.locator("#endNote").textContent()).trim();
  const kinds = await page.$$eval("#notes .kind", (els) => els.map((e) => e.textContent).join("·"));
  console.log("==", tag, "|", title, "| %:", pcts.join(" ") || "-", "| 잠금", locks, "|", kinds, end ? "| 끝: " + end.slice(0, 44) : "");
  if (expectTitle && !expectTitle.test(title)) problems.push(tag + ": 제목 " + title);
  if (/D조|C조|B조|A조/.test(hint) || locks) problems.push(tag + ": 급수/잠금");
};
await page.goto("file:///home/fgcp/personal/badmin-simulater/mobile/index.html"); await page.waitForTimeout(500);
await page.getByRole("button", { name: "단식", exact: true }).click(); await page.locator("#btnStart").click(); await page.waitForTimeout(2600);
console.log("탭:", await page.$$eval("#topics .tab", (ts) => ts.map((t) => t.textContent)));
await tab(/클리어·드롭 랠리/); await check("cd0", /상대 클리어 → 내 백핸드 뒤/); await shot("cd0");
await next(); await check("cd1 내 선택", /내 선택 — 백핸드 오버헤드/); await shot("cd1");
await pick(/^클리어 스트레이트/); await check("1구 클리어", /1구: 클리어/); await shot("cd2-clear");
await next(); await check("2 상대 응수", /상대 응수 예상/); await shot("cd2-opp");
await pick(/^빠른 드롭 → 내 앞/); await check("2구 상대 드롭", /2구: 상대 빠른 드롭/); await shot("cd2-opp-drop");
await next(); await check("3 내 다음 샷", /내 다음 샷/); await shot("cd3-next");
await pick(/^타이트 네트샷/); await check("3구 네트샷(끝)", /3구: 네트샷/); await shot("cd3-net-end");
await restart(); await next(); await pick(/^크로스 클리어/); await next(); await pick(/^얕은 클리어/); await next(); await check("3 얕은 클리어 뒤", /내 다음 샷/); await pick(/^스매시 사이드/); await check("3구 스매시(끝)", /3구: 스매시/); await shot("cd3-smash-end");
await tab(/스매시 수비/); await check("sd0", /뒤 코너로 리프트/); await shot("sd0");
await next(); await check("sd1 스매시 코스", /상대 스매시 — 어디로/); await shot("sd1");
await pick(/^직선/); await check("1 직선 스매시", /스매시 → 직선/); await shot("sd1-st");
await next(); await check("2 내 수비", /내 수비 — 포핸드/); await shot("sd2-st");
await pick(/^블록 → 코스/); await pick(/^크로스 블록/); await check("2구 크로스 블록", /2구: 블록/); await shot("sd2-block");
await next(); await check("3 상대 응수", /상대 응수 예상/); await shot("sd3-opp");
await pick(/^리프트 → 내 뒤/); await check("3구 리프트(전환 성공)", /3구: 상대 리프트/); await shot("sd3-lift-end");
await restart(); await next(); await pick(/^크로스/); await next(); await pick(/^드라이브 카운터/); await check("2구 드라이브", /2구: 드라이브/); await next(); await pick(/^블록 → 내 앞/); await check("3구 블록(끝)", /3구: 상대 블록/); await shot("sd3-drive-block-end");
console.log("버전:", await page.locator("#version").textContent());
console.log("문제:", problems.length ? problems : "없음");
console.log("page errors:", errors.length ? errors : "none");
await browser.close();
process.exit(problems.length || errors.length ? 1 : 0);
