// v1.1.1 확인: 공수 전환 이음새 스매시를 포핸드 쪽 수비수 O2가 받는 장면 — t1(O2 포핸드, 사용자 확인 노트), 블록/드라이브 카운터/리프트의 O2 타점, 비율.
import { chromium } from "playwright-core";
import { mkdirSync } from "node:fs";
import { homedir } from "node:os";
import { join } from "node:path";
const outDir = "/tmp/v111"; mkdirSync(outDir, { recursive: true });
const browser = await chromium.launch({ executablePath: join(homedir(), ".cache/ms-playwright/chromium-1223/chrome-linux64/chrome"), headless: true, args: ["--no-sandbox"] });
const page = await browser.newPage({ viewport: { width: 390, height: 844 }, deviceScaleFactor: 2, isMobile: true, hasTouch: true });
const errors = []; page.on("pageerror", (e) => errors.push(String(e)));
let n = 0; const shot = async (name) => { n += 1; await page.screenshot({ path: join(outDir, `${String(n).padStart(2, "0")}-${name}.png`) }); console.log("saved", name, "|", await page.locator("#stepTitle").textContent()); };
const next = async () => { await page.getByRole("button", { name: "다음" }).click(); await page.waitForTimeout(2200); };
const pick = async (re) => { await page.getByRole("button", { name: re }).click(); await page.waitForTimeout(2300); };
const buttons = () => page.$$eval("#branches button.branch", (bs) => bs.map((b) => b.querySelector(".lbl").textContent.replace(/ — .*?(?= \(|$)/, "").slice(0, 26) + " " + ((b.querySelector(".pct") || {}).textContent || "-") + (b.disabled ? " [disabled]" : "")));
const arrows = () => page.$$eval("#court line", (ls) => ls.filter((l) => l.getAttribute("stroke-width") === "0.09").length);
const prompt = async () => (await page.$("#branches .prompt")) ? page.locator("#branches .prompt").textContent() : "-";
const notes = () => page.$$eval("#notes li", (ls) => ls.map((l) => l.textContent.trim().replace(/\s+/g, " ").slice(0, 72)));
const title = () => page.locator("#stepTitle").textContent();
const setTier = async (t) => { await page.locator("#btnSettings").click(); await page.waitForTimeout(300); await page.getByRole("button", { name: t, exact: true }).click(); await page.locator("#btnStart").click(); await page.waitForTimeout(2600); };
const tab = async (re) => { await page.locator(".tab", { hasText: re }).click(); await page.waitForTimeout(2600); };
const log = async (tag) => console.log(tag, "|", await title(), "|", JSON.stringify(await buttons()), "| 화살표", await arrows(), "| prompt:", await prompt());
await page.goto("file:///home/fgcp/personal/badmin-simulater/mobile/index.html"); await page.waitForTimeout(500);
await page.getByRole("button", { name: "남복" }).click(); await page.getByRole("button", { name: "D조(초급)" }).click(); await page.locator("#btnStart").click(); await page.waitForTimeout(2600);
await tab(/공수 전환/); await next();
await log("D조 t1"); console.log("t1 노트:", JSON.stringify(await notes())); await shot("t1-D");
await pick(/가 블록/); console.log("t2block 노트:", JSON.stringify((await notes()).slice(0, 1))); await shot("t2block-D");
await next(); await shot("t3kill-D");
await tab(/공수 전환/); await next(); await pick(/나 드라이브 카운터/); await log("D조 t2drive"); console.log("t2drive 코스 노트:", JSON.stringify((await notes()).filter((x) => x.startsWith("코스")))); await shot("t2drive-D");
await pick(/늦어 네트 아래/); await next(); await log("D조 t4smash");
await tab(/공수 전환/); await next(); await pick(/다 리프트/); await shot("t2lift-D");
await setTier("A조"); await tab(/공수 전환/); await next(); await log("A조 t1"); await shot("t1-A");
console.log("version:", await page.locator("#version").textContent());
console.log("page errors:", errors.length ? errors : "none"); await browser.close();
