// v1.6 확인: 단식(급수 없음) — 시작 화면에서 단식을 고르면 급수 블록이 숨고 바로 시작, 헤더 '단식 ▾', 비율 힌트에 급수 없음, '불가' 없음, 급수 줄 없음.
// 경로 3개(클리어→내 클리어, 스매시→블록, 드롭→네트샷) + 복식 회귀(급수 블록 보임, 헤더에 급수). 사용: node scripts/shot-v16.mjs
import { chromium } from "playwright-core";
import { mkdirSync } from "node:fs";
import { homedir } from "node:os";
import { join } from "node:path";
const outDir = "/tmp/v16"; mkdirSync(outDir, { recursive: true });
const browser = await chromium.launch({ executablePath: join(homedir(), ".cache/ms-playwright/chromium-1223/chrome-linux64/chrome"), headless: true, args: ["--no-sandbox"] });
const page = await browser.newPage({ viewport: { width: 390, height: 844 }, deviceScaleFactor: 2, isMobile: true, hasTouch: true });
const errors = []; page.on("pageerror", (e) => errors.push(String(e)));
let n = 0; const shot = async (name) => { n += 1; await page.screenshot({ path: join(outDir, `${String(n).padStart(2, "0")}-${name}.png`) }); };
const next = async () => { await page.getByRole("button", { name: "다음" }).click(); await page.waitForTimeout(2200); };
const pick = async (re) => { await page.getByRole("button", { name: re }).click(); await page.waitForTimeout(2300); };
const restart = async () => { await page.getByRole("button", { name: "처음", exact: true }).click(); await page.waitForTimeout(1200); };
const problems = [];
const check = async (tag) => {
  const title = (await page.locator("#stepTitle").textContent()).trim();
  const hint = (await page.locator("#branches .est").count()) ? (await page.locator("#branches .est").textContent()).trim() : "";
  const locks = await page.locator("#branches .pct.lock").count();
  const tierLi = await page.locator("#notes .k-급수").count();
  const form = (await page.locator("#formation").textContent()).trim();
  const pcts = await page.$$eval("#branches .pct", (els) => els.map((e) => e.textContent));
  const note = (await page.locator("#courtNote").textContent()).trim();
  const kinds = await page.$$eval("#notes .kind", (els) => els.map((e) => e.textContent).join("·"));
  console.log("==", tag, "|", title, "|", form.slice(0, 40), "| 힌트:", hint || "-", "| %:", pcts.join(" "), "| 잠금", locks, "| 급수줄", tierLi, "|", kinds, "|", note);
  if (/D조|C조|B조|A조/.test(hint)) problems.push(tag + ": 힌트에 급수 " + hint);
  if (locks) problems.push(tag + ": 불가 " + locks);
  if (tierLi) problems.push(tag + ": 급수 줄 있음");
  if (!/^나:/.test(form)) problems.push(tag + ": 대형 라벨 " + form.slice(0, 10));
  if (!/^단식/.test(note)) problems.push(tag + ": 코트 설명 " + note);
};
await page.goto("file:///home/fgcp/personal/badmin-simulater/mobile/index.html"); await page.waitForTimeout(500);
await page.getByRole("button", { name: "단식", exact: true }).click(); await page.waitForTimeout(200);
const tierHidden = await page.$eval("#tierBlock", (el) => getComputedStyle(el).display === "none");
const startEnabled = await page.$eval("#btnStart", (b) => !b.disabled);
console.log("단식 선택: 급수 블록 숨김", tierHidden, "| 시작 가능", startEnabled);
if (!tierHidden || !startEnabled) problems.push("시작 화면: 급수 블록/시작 버튼");
await shot("start-singles");
await page.locator("#btnStart").click(); await page.waitForTimeout(2600);
console.log("헤더:", await page.locator("#btnSettings").textContent(), "| 탭:", await page.$$eval("#topics .tab", (ts) => ts.map((t) => t.textContent)));
await check("0 서브"); await shot("hs0");
await next(); await check("1 리턴 선택"); await shot("hs1");
await pick(/^클리어 → 코스/); await check("1 클리어 코스"); await shot("hs1-clear");
await pick(/내 백핸드 뒤/); await check("2 클리어→백핸드 뒤"); await shot("hs2-c-bh");
await next(); await check("3 내 3구(백핸드 오버헤드)"); await shot("hs3-c-bh");
await pick(/^클리어 — 대부분/); await check("3 클리어 코스"); await shot("hs3-c-bh-clear");
await pick(/크로스 \(상대 백핸드 뒤\)/); await check("마지막: 클리어 크로스"); await shot("leaf-clear-cross");
await restart(); await next(); await pick(/^스매시 → 코스/); await pick(/사이드 스트레이트/); await check("2 스매시 사이드"); await shot("hs2-s-st");
await next(); await check("3 스매시 수비 선택"); await shot("hs3-s-st");
await pick(/^블록 → 코스/); await pick(/크로스 블록/); await check("마지막: 크로스 블록"); await shot("leaf-block-cross");
await restart(); await next(); await pick(/^빠른 드롭 → 코스/); await pick(/스트레이트 \(내 백핸드 앞\)/); await next(); await check("3 드롭 뒤 선택"); await shot("hs3-d-bh");
await pick(/^타이트 네트샷/); await check("마지막: 타이트 네트샷"); await shot("leaf-net");
await restart(); await next(); await pick(/슬라이스/); await next(); await pick(/^리프트 → 코스/); await pick(/중앙 높게/); await check("마지막: 슬라이스→리프트"); await shot("leaf-slice-lift");
// 복식 회귀: 설정 열고 남복/여복 → 급수 블록 보이고 D조 필요
await page.locator("#btnSettings").click(); await page.waitForTimeout(400);
await page.getByRole("button", { name: "남복/여복", exact: true }).click(); await page.waitForTimeout(200);
const tierShown = await page.$eval("#tierBlock", (el) => getComputedStyle(el).display !== "none");
console.log("남복/여복 선택: 급수 블록 보임", tierShown);
if (!tierShown) problems.push("복식: 급수 블록 안 보임");
await page.getByRole("button", { name: "D조(초급)", exact: true }).click(); await page.locator("#btnStart").click(); await page.waitForTimeout(2600);
const hdr = await page.locator("#btnSettings").textContent(); console.log("복식 헤더:", hdr);
if (!/D조/.test(hdr)) problems.push("복식 헤더에 급수 없음");
await next(); const dblHint = (await page.locator("#branches .est").textContent()).trim(); console.log("복식 힌트:", dblHint);
if (!/D조/.test(dblHint)) problems.push("복식 힌트에 급수 없음");
await shot("dbl-regression");
console.log("버전:", await page.locator("#version").textContent());
console.log("문제:", problems.length ? problems : "없음");
console.log("page errors:", errors.length ? errors : "none");
await browser.close();
process.exit(problems.length || errors.length ? 1 : 0);
