import { chromium } from "playwright-core";
import { mkdirSync } from "node:fs";
import { homedir } from "node:os";
import { join } from "node:path";
const outDir = "/tmp/r4clear"; mkdirSync(outDir, { recursive: true });
const browser = await chromium.launch({ executablePath: join(homedir(), ".cache/ms-playwright/chromium-1223/chrome-linux64/chrome"), headless: true, args: ["--no-sandbox"] });
const page = await browser.newPage({ viewport: { width: 390, height: 844 }, deviceScaleFactor: 2, isMobile: true, hasTouch: true });
const errors = []; page.on("pageerror", (e) => errors.push(String(e)));
let n = 0; const shot = async (name) => { n += 1; await page.screenshot({ path: join(outDir, `${String(n).padStart(2, "0")}-${name}.png`) }); console.log("saved", name, "|", await page.locator("#stepTitle").textContent()); };
const next = async () => { await page.getByRole("button", { name: "다음" }).click(); await page.waitForTimeout(2200); };
const pick = async (re) => { await page.getByRole("button", { name: re }).click(); await page.waitForTimeout(2300); };
await page.goto("file:///home/fgcp/personal/badmin-simulater/mobile/index.html"); await page.waitForTimeout(500);
await page.getByRole("button", { name: "남복" }).click(); await page.getByRole("button", { name: "B조" }).click(); await page.locator("#btnStart").click(); await page.waitForTimeout(2000);
await page.getByRole("button", { name: /숏서브 · 리시브 측/ }).click(); await page.waitForTimeout(1600);
await next(); await next(); await pick(/4 리프트/); await next();
await pick(/클리어 — 너무/); await pick(/스트레이트 뒤 코너/); await shot("r4-clear-straight-R-takes");
await page.getByRole("button", { name: "이전" }).click(); await page.waitForTimeout(2000);
await pick(/크로스 뒤 코너/); await shot("r4-clear-cross-RP-takes");
await page.getByRole("button", { name: /숏서브 · 서브 측/ }).click(); await page.waitForTimeout(1600);
await next(); await pick(/D 리프트/); await next(); await pick(/클리어 — 너무/); await pick(/스트레이트 뒤 코너/); await shot("D1-clear-straight-R-takes");
console.log("page errors:", errors.length ? errors : "none"); await browser.close();
