// v1.2 확인: 선수 이름 한글(서버·파트너·리시버·파트너 / 나·파트너·상대 전위·후위 / 나·파트너·상대1·2) — 코트 원 라벨, 질문 꼬리, 면 설명 줄, 코스 라벨, 3구 생성 문장, 대형 문구.
import { chromium } from "playwright-core";
import { mkdirSync } from "node:fs";
import { homedir } from "node:os";
import { join } from "node:path";
const outDir = "/tmp/v12"; mkdirSync(outDir, { recursive: true });
const browser = await chromium.launch({ executablePath: join(homedir(), ".cache/ms-playwright/chromium-1223/chrome-linux64/chrome"), headless: true, args: ["--no-sandbox"] });
const page = await browser.newPage({ viewport: { width: 390, height: 844 }, deviceScaleFactor: 2, isMobile: true, hasTouch: true });
const errors = []; page.on("pageerror", (e) => errors.push(String(e)));
let n = 0; const shot = async (name) => { n += 1; await page.screenshot({ path: join(outDir, `${String(n).padStart(2, "0")}-${name}.png`) }); console.log("saved", name, "|", await page.locator("#stepTitle").textContent()); };
const next = async () => { await page.getByRole("button", { name: "다음" }).click(); await page.waitForTimeout(2200); };
const pick = async (re) => { await page.getByRole("button", { name: re }).click(); await page.waitForTimeout(2300); };
const buttons = () => page.$$eval("#branches button.branch", (bs) => bs.map((b) => b.querySelector(".lbl").textContent.slice(0, 40) + " " + ((b.querySelector(".pct") || {}).textContent || "-") + (b.disabled ? " [disabled]" : "")));
const prompt = async () => (await page.$("#branches .prompt")) ? page.locator("#branches .prompt").textContent() : "-";
const notes = () => page.$$eval("#notes li", (ls) => ls.map((l) => l.textContent.trim().replace(/\s+/g, " ").slice(0, 90)));
const labels = () => page.$$eval("#court g.player text", (ts) => ts.map((t) => t.textContent + "@" + t.getAttribute("font-size")));
const formation = () => page.locator(".formation").textContent();
const title = () => page.locator("#stepTitle").textContent();
const setTier = async (t) => { await page.locator("#btnSettings").click(); await page.waitForTimeout(300); await page.getByRole("button", { name: t, exact: true }).click(); await page.locator("#btnStart").click(); await page.waitForTimeout(2600); };
const tab = async (re) => { await page.locator(".tab", { hasText: re }).click(); await page.waitForTimeout(2600); };
const idRe = /(?<![A-Za-z0-9_])(RP|OF|OB|O1|O2|S|P|R|F|B)(?![A-Za-z0-9_])(?!-[A-Z0-9])(?!조)/;
const leftovers = [];
const log = async (tag) => {
  const t = await title(), f = await formation(), pr = await prompt(), bs = await buttons(), ns = await notes(), ls = await labels();
  console.log(tag, "|", t, "|", f, "| prompt:", pr, "|", JSON.stringify(bs), "| 원:", ls.join(" "));
  [t, f, pr, ...bs, ...ns].forEach((s) => { if (idRe.test(s)) leftovers.push(tag + ": " + s); });
};
await page.goto("file:///home/fgcp/personal/badmin-simulater/mobile/index.html"); await page.waitForTimeout(500);
await page.getByRole("button", { name: "남복" }).click(); await page.getByRole("button", { name: "D조(초급)" }).click(); await page.locator("#btnStart").click(); await page.waitForTimeout(2600);
await log("서브 측 0"); await shot("serve0");
await next(); await log("서브 측 초구 응수(리시버)"); console.log("노트:", JSON.stringify(await notes())); await shot("serve-reply");
await pick(/^A 푸시/); await log("서브 측 푸시 코스"); await shot("serve-Acourse");
await pick(/A-2 크로스/); await next(); await log("3구(서버 파트너)"); console.log("노트:", JSON.stringify(await notes())); await shot("serve-third-P");
await pick(/푸시/); await log("3구 푸시 코스"); await shot("serve-third-course");
await pick(/뒤 코너|스트레이트/); await log("3구 잎"); console.log("노트:", JSON.stringify(await notes())); await shot("serve-third-leaf");
await tab(/숏서브 · 리시브 측/); await next(); await next(); await log("리시브 측 초구 선택"); await shot("recv-choice");
await tab(/롱 서브 · 서브 측/); await pick(/F-A/); await log("롱 서브 F-A(서버 파트너 백핸드)"); console.log("노트:", JSON.stringify(await notes())); await shot("flick-fA1");
await tab(/드라이브 랠리/); await log("드라이브 0"); console.log("노트:", JSON.stringify(await notes())); await shot("drive0");
await next(); await pick(/내가 앞에서/); await log("드라이브 dr2f(나 백핸드)"); console.log("노트:", JSON.stringify(await notes())); await shot("drive-dr2f");
await tab(/공수 전환/); await log("공수 전환 0"); await shot("trans0");
await next(); await log("공수 전환 t1(상대2 포핸드)"); console.log("노트:", JSON.stringify(await notes())); await shot("trans-t1");
await pick(/나 드라이브 카운터/); await log("t2drive(나 포핸드)"); await shot("trans-t2drive");
await pick(/늦어 네트 아래/); await next(); await log("t4smash(내 수비)"); console.log("노트:", JSON.stringify(await notes())); await shot("trans-t4smash");
await pick(/블록/); await next(); await log("t6reattack(역할 교대)"); console.log("노트:", JSON.stringify(await notes())); await shot("trans-t6");
await setTier("A조"); await tab(/공수 전환/); await next(); await log("A조 t1");
console.log("version:", await page.locator("#version").textContent());
console.log("약자 잔존:", leftovers.length ? leftovers : "없음");
console.log("page errors:", errors.length ? errors : "none"); await browser.close();
