// v0.7 확인: 3구 기술→코스 갈래(서브 측·리시브 측) 화살표+비율, 4구 연결. 사용: node scripts/shot-v07.mjs /tmp/v07shots
import { chromium } from "playwright-core";
import { mkdirSync } from "node:fs";
import { homedir } from "node:os";
import { join } from "node:path";

const [outDir = "/tmp/v07shots"] = process.argv.slice(2);
mkdirSync(outDir, { recursive: true });
const browser = await chromium.launch({ executablePath: join(homedir(), ".cache/ms-playwright/chromium-1223/chrome-linux64/chrome"), headless: true, args: ["--no-sandbox"] });
const page = await browser.newPage({ viewport: { width: 390, height: 844 }, deviceScaleFactor: 2, isMobile: true, hasTouch: true });
const errors = [];
page.on("pageerror", (e) => errors.push(String(e)));
page.on("console", (m) => { if (m.type() === "error") errors.push(m.text()); });
let n = 0;
const title = async () => (await page.locator("#stepTitle").textContent().catch(() => "")) || "";
const shot = async (name) => { n += 1; const f = join(outDir, `${String(n).padStart(2, "0")}-${name}.png`); await page.screenshot({ path: f }); console.log("saved", f, "|", (await title()).slice(0, 40)); };
const next = async () => { await page.getByRole("button", { name: "다음" }).click(); await page.waitForTimeout(2200); };
const pick = async (re) => { await page.getByRole("button", { name: re }).click(); await page.waitForTimeout(2300); };
const tab = async (re) => { await page.getByRole("button", { name: re }).click(); await page.waitForTimeout(1600); };
const pcts = async () => page.$$eval(".branch", (bs) => bs.map((b) => (b.querySelector(".lbl")?.textContent || "").slice(0, 12) + " " + (b.querySelector(".pct")?.textContent || "-")));
const arrows = async () => page.$$eval("#court g:nth-of-type(3) line", (ls) => ls.length);
const hasNext = async () => page.$$eval("button", (bs) => bs.some((b) => b.textContent.trim() === "다음" && !b.disabled && b.offsetParent !== null));

await page.goto("file:///home/fgcp/personal/badmin-simulater/mobile/index.html");
await page.waitForTimeout(500);
await page.getByRole("button", { name: "남복" }).click();
await page.getByRole("button", { name: "B조" }).click();
await page.locator("#btnStart").click();
await page.waitForTimeout(2300);
console.log("version:", await page.locator("#version").textContent());
// 서브 측: 서브 → reply → A 푸시 → 스트레이트 → A1 → 3구 기술 선택
await next();
await pick(/A 푸시/);
await pick(/스트레이트/);
await shot("A1-straight-push");
await next();
await shot("A1_3-tech-choice");
console.log("A1_3 B조:", await pcts(), "arrows:", await arrows());
await pick(/푸시 — 네트 높이/);
await shot("A1_3-push-course");
console.log("A1_3_push B조:", await pcts(), "arrows:", await arrows());
await pick(/스트레이트 트램라인/);
await shot("A1_3-push-straight-leaf");
console.log("leaf next enabled:", await hasNext());
await page.getByRole("button", { name: "이전" }).click(); await page.waitForTimeout(2000);
await page.getByRole("button", { name: "이전" }).click(); await page.waitForTimeout(2000);
await pick(/리프트 — 붙일 수 없을 때/);
await pick(/크로스 뒤 코너/);
await shot("A1_3-lift-cross-leaf-arrow");
// 처음 → 리프트 갈래 → D1 → 3구(스매시/드롭/클리어) → 스매시 → 센터 → 4구 갈래 유지
await page.getByRole("button", { name: "처음" }).click(); await page.waitForTimeout(1800);
await next();
await pick(/D 리프트/);
await next();
await shot("D1_3-overhead-choice");
console.log("D1_3 B조:", await pcts(), "arrows:", await arrows());
await pick(/스매시 — 좋은/);
await shot("D1_3-smash-course");
console.log("D1_3_smash B조:", await pcts(), "arrows:", await arrows());
await pick(/센터 \(두 수비/);
await shot("D1_3-smash-centre-4th-branches");
console.log("after smash centre:", await pcts());
await pick(/D-2 상대 깊은 리프트/);
await shot("D3b-reached");
// C 네트샷 중앙 → 3구 킬/네트/리프트
await page.getByRole("button", { name: "처음" }).click(); await page.waitForTimeout(1800);
await next();
await pick(/C 네트샷/);
await pick(/중앙/);
await next();
await shot("C1_3-net-choice");
console.log("C1_3 B조:", await pcts(), "arrows:", await arrows());
await pick(/킬 — 테이프/);
await shot("C1_3-kill-course");
console.log("C1_3_kill B조:", await pcts());
// 리시브 측: 서브인 → 선택 → 푸시 → 스트레이트 → r1 → 상대 3구
await tab(/숏서브 · 리시브 측/);
await next(); await next();
await pick(/1 푸시/);
await pick(/스트레이트/);
await next();
await shot("r1_3-opponent-choice");
console.log("r1_3 B조:", await pcts(), "arrows:", await arrows());
await pick(/드라이브 — 네트보다/);
await shot("r1_3-drive-course");
await pick(/상대 몸/);
await shot("r1_3-drive-body-leaf");
console.log("r1 drive body next enabled:", await hasNext());
await next();
await shot("r1a2-reached");
// r3 중앙 네트샷 → 상대 리프트 스트레이트 → r3b2 스매시
await page.getByRole("button", { name: "처음" }).click(); await page.waitForTimeout(1800);
await next(); await next();
await pick(/3 네트샷/);
await pick(/중앙/);
await next();
await pick(/리프트 — 붙일 수 없을 때/);
await shot("r3_3-lift-course");
await pick(/스트레이트 뒤 코너/);
await shot("r3_3-lift-straight-leaf-arrow");
await next();
await shot("r3b2-reached");
// r4 리프트 → 상대 스매시 → 스트레이트 → 수비 3갈래
await page.getByRole("button", { name: "처음" }).click(); await page.waitForTimeout(1800);
await next(); await next();
await pick(/4 리프트/);
await next();
await shot("r4_3-overhead-choice");
console.log("r4_3 B조:", await pcts(), "arrows:", await arrows());
await pick(/스매시 — 좋은/);
await pick(/스트레이트 \(코너/);
await shot("r4_3-smash-straight-defence-branches");
console.log("after r4 smash straight:", await pcts());
// 급수 D조로 바꿔 같은 화면 비율 변화
await page.locator("#btnSettings").click(); await page.waitForTimeout(200);
await page.getByRole("button", { name: "D조" }).click();
await page.getByRole("button", { name: "시작" }).click(); await page.waitForTimeout(600);
console.log("after r4 smash straight D조:", await pcts());
console.log("page errors:", errors.length ? errors : "none");
await browser.close();
