// v0.5 확인: 초구 코스 갈래(서브 측·리시브 측) + 드라이브 랠리 + 공수 전환 랠리. 사용: node scripts/shot-v05.mjs /tmp/v05shots
import { chromium } from "playwright-core";
import { mkdirSync } from "node:fs";
import { homedir } from "node:os";
import { join } from "node:path";

const [outDir = "/tmp/v05shots"] = process.argv.slice(2);
mkdirSync(outDir, { recursive: true });
const browser = await chromium.launch({ executablePath: join(homedir(), ".cache/ms-playwright/chromium-1223/chrome-linux64/chrome"), headless: true, args: ["--no-sandbox"] });
const page = await browser.newPage({ viewport: { width: 390, height: 844 }, deviceScaleFactor: 2, isMobile: true, hasTouch: true });
const errors = [];
page.on("pageerror", (e) => errors.push(String(e)));
page.on("console", (m) => { if (m.type() === "error") errors.push(m.text()); });
let n = 0;
const shot = async (name) => { n += 1; const f = join(outDir, `${String(n).padStart(2, "0")}-${name}.png`); await page.screenshot({ path: f }); console.log("saved", f, "|", await page.locator("#stepTitle").textContent()); };
const next = async () => { await page.getByRole("button", { name: "다음" }).click(); await page.waitForTimeout(2200); };
const prev = async () => { await page.getByRole("button", { name: "이전" }).click(); await page.waitForTimeout(2200); };
const pick = async (re) => { await page.getByRole("button", { name: re }).click(); await page.waitForTimeout(2300); };
const tab = async (re) => { await page.getByRole("button", { name: re }).click(); await page.waitForTimeout(1600); };

await page.goto("file:///home/fgcp/personal/badmin-simulater/mobile/index.html");
await page.waitForTimeout(500);
// v0.6 시작 화면: 종목·급수 고르고 시작
await page.getByRole("button", { name: "남복" }).click();
await page.getByRole("button", { name: "B조" }).click();
await page.locator("#btnStart").click();
await page.waitForTimeout(2200);
console.log("tabs:", await page.$$eval(".tab", (b) => b.map((x) => x.textContent)));
// 서브 측: 초구 → 푸시 코스
await next();
await shot("serve-reply-branches");
await pick(/A 푸시/);
await shot("serve-Acourse");
await pick(/A-3 서버/);
await shot("serve-A1b-body-push");
await next();
await shot("serve-A2b-block");
await prev(); await prev();
await pick(/A-4 뒤 코너/);
await next();
await shot("serve-A2c-rear-corner-response");
await page.getByRole("button", { name: "처음" }).click(); await page.waitForTimeout(2200);
await next();
await pick(/C 네트샷/);
await shot("serve-Ccourse");
await pick(/C-3 크로스/);
await shot("serve-C1x-cross-net");
await next();
await shot("serve-C2x");
await prev(); await prev();
await pick(/C-1 스트레이트/);
await shot("serve-C1s-straight-net");
// 리시브 측
await tab(/숏서브 · 리시브 측/);
await next(); await next();
await shot("recv-choice");
await pick(/^1 푸시/);
await shot("recv-pushCourse");
await pick(/1-1 스트레이트/);
await shot("recv-r1-straight-push");
await prev();
await pick(/1-4 뒤 코너/);
await next();
await shot("recv-r1corner2-they-lift");
await page.getByRole("button", { name: "처음" }).click(); await page.waitForTimeout(2200);
await next(); await next();
await pick(/^3 네트샷/);
await shot("recv-netCourse");
// 드라이브 랠리
await tab(/드라이브 랠리/);
await shot("drive-dr0");
await next();
await shot("drive-dr1-branches");
await pick(/가 F가/);
await shot("drive-dr2f-choice");
await pick(/푸시 — 네트 높이/);
await next();
await shot("drive-dr4lift");
await page.getByRole("button", { name: "처음" }).click(); await page.waitForTimeout(1600);
await next();
await pick(/다 네트 아래로/);
await pick(/리프트 → 즉시 좌우/);
await shot("drive-dr3lift-red-arrow");
// 공수 전환 랠리
await tab(/공수 전환 랠리/);
await shot("trans-t0-smash");
await next();
await shot("trans-t1-branches");
await pick(/나 드라이브 카운터/);
await shot("trans-t2drive");
await pick(/B가 늦어/);
await shot("trans-t3ourlift-red-arrow");
await next();
await shot("trans-t4smash-4branches");
await pick(/^블록/);
await next();
await shot("trans-t6reattack-updown-arrow");
console.log("page errors:", errors.length ? errors : "none");
await browser.close();
